// Central environment configuration with sensible defaults.
// All AI-service-related knobs live here so they can be tuned per
// deployment without touching code. See docs/AI_FEATURE.md for guidance on
// each value.

function bool(value, fallback) {
    if (value === undefined || value === null || value === "") return fallback;
    return ["1", "true", "yes", "on"].includes(String(value).toLowerCase());
}

function int(value, fallback) {
    const n = parseInt(value, 10);
    return Number.isFinite(n) ? n : fallback;
}

function list(value, fallback) {
    if (!value) return fallback;
    return value.split(",").map((s) => s.trim()).filter(Boolean);
}

const config = {
    port: int(process.env.PORT, 3000),
    nodeEnv: process.env.NODE_ENV || "development",

    // Feature flag: set to false to fully disable the new transcribe/translate
    // routes and revert to the pre-existing static app (rollback lever).
    enableAiFeatures: bool(process.env.ENABLE_AI_FEATURES, true),

    // Public-facing access control
    allowedOrigins: list(process.env.ALLOWED_ORIGINS, []),
    requireClientApiKey: bool(process.env.REQUIRE_CLIENT_API_KEY, false),
    clientApiKey: process.env.CLIENT_API_KEY || "",

    // Service-to-service auth shared with the Python AI services
    internalServiceToken: process.env.INTERNAL_SERVICE_TOKEN || "",

    // AI service endpoints (internal network in production)
    transcriptionServiceUrl: process.env.TRANSCRIPTION_SERVICE_URL || "http://localhost:8001",
    translationServiceUrl: process.env.TRANSLATION_SERVICE_URL || "http://localhost:8002",

    // Mutual TLS for the gateway<->AI-service link. Off by default for a
    // zero-config local/native run; docker-compose.yml turns this on and
    // wires up certs generated by scripts/generate-internal-certs.sh. When
    // enabled, the service URLs above must be https://.
    internalTlsEnabled: bool(process.env.INTERNAL_TLS_ENABLED, false),
    internalTlsClientCertFile: process.env.INTERNAL_TLS_CLIENT_CERT_FILE || "",
    internalTlsClientKeyFile: process.env.INTERNAL_TLS_CLIENT_KEY_FILE || "",
    internalTlsCaFile: process.env.INTERNAL_TLS_CA_FILE || "",

    // Timeouts
    transcribeTimeoutMs: int(process.env.TRANSCRIBE_TIMEOUT_MS, 120000),
    translateTimeoutMs: int(process.env.TRANSLATE_TIMEOUT_MS, 30000),
    aiHealthTimeoutMs: int(process.env.AI_HEALTH_TIMEOUT_MS, 3000),

    // Input limits
    maxAudioUploadMb: int(process.env.MAX_AUDIO_UPLOAD_MB, 100),
    maxTranslateTextLength: int(process.env.MAX_TRANSLATE_TEXT_LENGTH, 20000),

    // Gateway-side concurrency guards (defense in depth, the AI services
    // also enforce their own semaphores)
    maxConcurrentTranscribeRequests: int(process.env.MAX_CONCURRENT_TRANSCRIBE_REQUESTS, 4),
    maxConcurrentTranslateRequests: int(process.env.MAX_CONCURRENT_TRANSLATE_REQUESTS, 8),

    // Rate limiting
    rateLimitWindowMs: int(process.env.RATE_LIMIT_WINDOW_MS, 60000),
    rateLimitTranscribeMax: int(process.env.RATE_LIMIT_TRANSCRIBE_MAX, 10),
    rateLimitTranslateMax: int(process.env.RATE_LIMIT_TRANSLATE_MAX, 20),
    rateLimitGeneralMax: int(process.env.RATE_LIMIT_GENERAL_MAX, 60),

    logLevel: process.env.LOG_LEVEL || "info",

    // Recording history (persistent storage - see docs/AI_FEATURE.md for the
    // data-retention policy this implies). SQLite file + a permanent audio
    // directory, both expected to live on a mounted volume in production.
    dbPath: process.env.DB_PATH || "",
    recordingsDir: process.env.RECORDINGS_DIR || "",
    recordingsRetentionDays: int(process.env.RECORDINGS_RETENTION_DAYS, 0), // 0 = keep forever

    // Default language pair when a request doesn't specify one.
    defaultSourceLanguage: process.env.DEFAULT_SOURCE_LANGUAGE || "ur",
    defaultTargetLanguage: process.env.DEFAULT_TARGET_LANGUAGE || "en",
};

module.exports = config;
